#!/bin/bash

echo
echo "initializing ray environment..."
cd /opt/ray
. $(pipenv --venv)/bin/activate

echo
echo "starting ray worker..."
echo

ray --logging-level=info \
    start \
    --address=${RAY_HEAD_NODE}:6379 \
    --node-ip-address=$RAY_POD_IP \
    --num-cpus=$RAY_CPU_REQUEST \
    --object-manager-port=12345 --node-manager-port=12346 \
    --log-style=record --log-color=false \
    --block
