# what is this?
#operator_role:
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ray-operator-serviceaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-operator-role
rules:
- apiGroups: ["", "cluster.ray.io"]
  resources: ["rayclusters", "rayclusters/finalizers", "rayclusters/status", "pods", "pods/exec", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: ray-operator-serviceaccount
roleRef:
  kind: Role
  name: ray-operator-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Pod
apiVersion: v1
metadata:
  name: ray-operator-pod
spec:
  serviceAccountName: ray-operator-serviceaccount
  containers:
  - name: ray
    imagePullPolicy: Always
    image: 'quay.io/erikerlandson/ray-operator-ubi:py-3.6-ray-43570553'
    command: [ '/bin/bash', '-c', '--', 'cd /opt/ray && pipenv run ray-operator' ]
    env:
    - name: RAY_CONFIG_DIR
      value: '/tmp/ray_cluster_configs'
    - name: RAY_OPERATOR_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
